openapi: 3.0.0
info:
  title: QrackNet API
  description: A RESTful API to expose Qrack library (https://github.com/unitaryfund/qrack) simulator functionality to
    users via the web
  version: 0.1.0
servers:
  - url: https://qrack.net/api
    description: Main (production) server
paths:
  /qrack:
    post:
      summary: Dispatches a QrackNet (JSON) script
      description: Dispatches a JSON "script" according to definition at
        https://github.com/vm6502q/qrack.net/blob/main/api/README.md
      operationId: dispatchJobForUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                program:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      parameters:
                        type: array
                        items:
                          oneOf:
                            - type: string
                            - type: boolean
                            - type: number
                            - type: array
                              items:
                                type: number
      responses:
        "200":
          description: Created new job for user
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      userId:
                        type: integer
                      jobStatusTypeId:
                        type: integer
                      statusMessage:
                        type: string
                      updatedAt:
                        type: string
                      createdAt:
                        type: string
  /qrack/{jobId}:
    get:
      summary: Returns the status and result of the job
      description: Returns the status and boolean, numerical or multi-dimensional numerical result of the job
      operationId: getJobForUser
      responses:
        "200":
          description: Reports whether the job is running, successfully completed, or failed, and gives a "result" object
            containing output.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      status:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
                          message:
                            type: string
                      result:
                        oneOf:
                          - type: boolean
                          - type: number
                          - type: array
                            items:
                              type: number
